from pathlib import Path
p=Path('backend/db.js')
s=p.read_text(encoding='utf-8')
repls=[
("d.products.forEach(p => { if (p.specification === undefined) p.specification = ''; if (p.material === undefined) p.material = ''; if (p.corrugation === undefined) p.corrugation = ''; if (p.weight === undefined) p.weight = 0; if (p.length === undefined) p.length = 0; if (p.width === undefined) p.width = 0; if (p.layers === undefined) p.layers = 0; if (p.deleted_at === undefined) p.deleted_at = null; if (p.unit === undefined) p.unit = '件'; if (typeof p.price !== 'number') p.price = Number(p.price) || 0; });", "d.products.forEach(p => { if (p.specification === undefined) p.specification = ''; if (p.material === undefined) p.material = ''; if (p.corrugation === undefined) p.corrugation = ''; if (p.weight === undefined) p.weight = 0; if (p.length === undefined) p.length = 0; if (p.width === undefined) p.width = 0; if (p.layers === undefined) p.layers = 0; if (p.deleted_at === undefined) p.deleted_at = null; if (p.unit === undefined) p.unit = '件'; if (typeof p.price !== 'number') p.price = Number(p.price) || 0; if (p.profile_updated_at === undefined) p.profile_updated_at = Number(p.updated_at) || Number(p.created_at) || 0; if (p.stock_updated_at === undefined) p.stock_updated_at = Number(p.updated_at) || Number(p.created_at) || 0; });"),
("l.sort((a,b) => (b.updated_at||0)-(a.updated_at||0) || b.id-a.id);", "l.sort((a,b) => (b.profile_updated_at||b.updated_at||0)-(a.profile_updated_at||a.updated_at||0) || b.id-a.id);"),
("created_at: now, updated_at: now\n  };", "created_at: now, updated_at: now, profile_updated_at: now, stock_updated_at: now\n  };"),
("function updateProduct(id, d) {\n  const p = getProduct(id); if (!p) throw new Error('商品不存在');", "function updateProduct(id, d) {\n  const p = getProduct(id); if (!p) throw new Error('商品不存在');\n  const beforeProfile = JSON.stringify({ name: p.name, category: p.category, specification: p.specification, material: p.material, corrugation: p.corrugation, weight: p.weight, length: p.length, width: p.width, layers: p.layers, unit: p.unit, price: p.price, safety_stock: p.safety_stock, supplier_id: p.supplier_id, image_url: p.image_url });"),
("  p.updated_at = Date.now(); persist(); return p;", "  const now = Date.now(); p.updated_at = now;\n  const afterProfile = JSON.stringify({ name: p.name, category: p.category, specification: p.specification, material: p.material, corrugation: p.corrugation, weight: p.weight, length: p.length, width: p.width, layers: p.layers, unit: p.unit, price: p.price, safety_stock: p.safety_stock, supplier_id: p.supplier_id, image_url: p.image_url });\n  if (beforeProfile !== afterProfile) p.profile_updated_at = now;\n  persist(); return p;", 1),
("p.stock=counted;p.updated_at=createdAt;", "p.stock=counted;p.updated_at=createdAt;p.stock_updated_at=createdAt;"),
("product.stock = after; product.updated_at = createdAt;", "product.stock = after; product.updated_at = createdAt; product.stock_updated_at = createdAt;"),
("p.stock = roundDecimal(p.stock + (tx.type === 'in' ? -tx.quantity : tx.quantity), 6); p.updated_at = Date.now();", "p.stock = roundDecimal(p.stock + (tx.type === 'in' ? -tx.quantity : tx.quantity), 6); p.updated_at = Date.now(); p.stock_updated_at = p.updated_at;"),
("created_at: now, updated_at: now\n  };\n  cache.customers.push", "created_at: now, updated_at: now, profile_updated_at: now, balance_updated_at: debt > 0 ? now : 0\n  };\n  cache.customers.push"),
("function updateCustomer(id, d) {\n  const c = getCustomer(id); if (!c) throw new Error('客户不存在');", "function updateCustomer(id, d) {\n  const c = getCustomer(id); if (!c) throw new Error('客户不存在');\n  const beforeProfile = JSON.stringify({ name: c.name, contact: c.contact, phone: c.phone, address: c.address, remark: c.remark });"),
("  c.updated_at = Date.now(); persist(); return c;", "  const now = Date.now(); c.updated_at = now;\n  const afterProfile = JSON.stringify({ name: c.name, contact: c.contact, phone: c.phone, address: c.address, remark: c.remark });\n  if (beforeProfile !== afterProfile) c.profile_updated_at = now;\n  if (d.debt !== undefined) c.balance_updated_at = now;\n  persist(); return c;", 1),
("created_at:now, updated_at:now };\n  cache.suppliers", "created_at:now, updated_at:now, profile_updated_at:now, balance_updated_at: payable > 0 ? now : 0 };\n  cache.suppliers"),
("function updateSupplier(id,d) {\n  const s = getSupplier(id); if (!s) throw new Error('供应商不存在');", "function updateSupplier(id,d) {\n  const s = getSupplier(id); if (!s) throw new Error('供应商不存在');\n  const beforeProfile = JSON.stringify({ name: s.name, contact: s.contact, phone: s.phone, address: s.address, remark: s.remark });"),
("  s.updated_at=Date.now(); persist(); return s;", "  const now = Date.now(); s.updated_at=now;\n  const afterProfile = JSON.stringify({ name: s.name, contact: s.contact, phone: s.phone, address: s.address, remark: s.remark });\n  if (beforeProfile !== afterProfile) s.profile_updated_at = now;\n  if (d.payable !== undefined) s.balance_updated_at = now;\n  persist(); return s;", 1)
]
for item in repls:
 old,new,*rest=item; count=rest[0] if rest else -1
 if old not in s: print('MISSING',old[:80]); continue
 s=s.replace(old,new,count)
p.write_text(s,encoding='utf-8')
