const { test } = require('node:test');
const assert = require('node:assert/strict');
const fs = require('node:fs');
const os = require('node:os');
const path = require('node:path');
const express = require('express');
const install = require('./team');

test('shared warehouse authorization, idempotency, conflicts, persistence and rollback', async () => {
  const dir = fs.mkdtempSync(path.join(os.tmpdir(), 'warehouse-team-test-'));
  process.env.WAREHOUSE_DATA_FILE = path.join(dir, 'data.json');
  process.env.WAREHOUSE_ACCOUNTS_FILE = path.join(dir, 'accounts.json');
  fs.writeFileSync(process.env.WAREHOUSE_DATA_FILE, JSON.stringify({ products:[],customers:[],suppliers:[],transactions:[],orders:[],ledger:[],_meta:{nextProductId:1,nextCustomerId:1,nextSupplierId:1,nextTransactionId:1,nextLedgerId:1} }));
  const initial = fs.readFileSync(process.env.WAREHOUSE_DATA_FILE,'utf8');
  await install.bootstrap(process.env.WAREHOUSE_ACCOUNTS_FILE, 'Example-test-password!');
  const db = require('./db');
  assert.equal(fs.readFileSync(process.env.WAREHOUSE_DATA_FILE,'utf8'),initial);
  const app=express();app.use(express.json());app.use('/api',install(db));
  const server=app.listen(0,'127.0.0.1');await new Promise(r=>server.once('listening',r));
  const origin=`http://127.0.0.1:${server.address().port}/api`;
  let imageProductId = null;
  async function call(url, method='GET', body, token='', rev, key) {
    const headers={'Content-Type':'application/json',Authorization:`Bearer ${token}`};
    if (rev!==undefined) headers['If-Match']=String(rev);
    if(key) headers['Idempotency-Key']=key;
    const r=await fetch(origin+url,{method,headers,body:body===undefined?undefined:JSON.stringify(body)});
    return {status:r.status,body:await r.json(),revision:r.headers.get('x-warehouse-revision'),requestId:r.headers.get('x-request-id'),security:{nosniff:r.headers.get('x-content-type-options'),frame:r.headers.get('x-frame-options'),referrer:r.headers.get('referrer-policy')}};
  }
  try {
    const health = await call('/health');
    assert.equal(health.status, 200);
    assert.match(health.requestId || '', /^[0-9a-f-]{36}$/);
    assert.equal(health.security.nosniff, 'nosniff');
    assert.equal(health.security.frame, 'DENY');
    assert.equal(health.security.referrer, 'no-referrer');
    assert.equal(health.body.data.online, true);
    assert.equal(health.body.data.dataReadable, true);
    assert.equal(health.body.data.dataWritable, true);
    assert.equal(health.body.data.accountsAvailable, true);
    assert.equal(Object.prototype.hasOwnProperty.call(health.body.data, 'path'), false);
    assert.equal((await call('/products')).status,401);
    assert.equal((await call('/auth/gate','POST',{password:'shuguang2026'})).status,200);
    assert.equal((await call('/auth/login','POST',{username:'admin',password:'Wrong-password-123'})).status,401);
    const admin=(await call('/auth/login','POST',{username:'admin',password:'Example-test-password!'})).body.data.token;
    const backupBefore = db.backupData();
    const malformedBackupKey = await call('/backup','POST',{data:backupBefore},admin,0,'bad');
    assert.equal(malformedBackupKey.status,400);
    assert.match(malformedBackupKey.body.message,/提交编号/);
    assert.deepEqual(db.backupData(),backupBefore);
    assert.equal((await call('/transactions?from=not-a-timestamp', 'GET', undefined, admin)).status, 400);
    assert.equal((await call('/ledger?type=unknown', 'GET', undefined, admin)).status, 400);
    assert.equal((await call('/transactions?from=20&to=10', 'GET', undefined, admin)).status, 400);
    const badJson = await fetch(origin + '/products', { method: 'POST', headers: { Authorization: `Bearer ${admin}`, 'Idempotency-Key': 'bad-json-body-0001', 'If-Match': '0' }, body: '[]' });
    assert.equal(badJson.status, 400);
    const tooLong = await call('/products', 'POST', { name: 'x'.repeat(51) }, admin, 0, 'too-long-name-0001');
    assert.equal(tooLong.status, 400);
    const badPhone = await call('/customers', 'POST', { name: 'Phone test', phone: 'abc' }, admin, 0, 'bad-phone-00001');
    assert.equal(badPhone.status, 400);
    const syncFirst = await fetch(origin + '/sync', { headers: { Authorization: `Bearer ${admin}` } });
    assert.equal(syncFirst.status, 200);
    const syncEtag = syncFirst.headers.get('etag');
    assert.match(syncEtag || '', /^"\d+"$/);
    const syncAgain = await fetch(origin + '/sync', { headers: { Authorization: `Bearer ${admin}`, 'If-None-Match': syncEtag } });
    assert.equal(syncAgain.status, 304);
    assert.equal(syncAgain.headers.get('x-warehouse-revision'), syncEtag.replaceAll('"', ''));
    for(const role of ['operator','viewer']) assert.equal((await call('/team','POST',{username:role,password:'Example-test-password!',role},admin)).status,200);
    const operator=(await call('/auth/login','POST',{username:'operator',password:'Example-test-password!'})).body.data.token;
    const viewer=(await call('/auth/login','POST',{username:'viewer',password:'Example-test-password!'})).body.data.token;
    assert.equal((await call('/products','POST',{name:'x'},viewer,0,'viewer-request-0001')).status,403);
    assert.equal((await call('/team','GET',undefined,operator)).status,403);
    let created=await call('/products','POST',{name:'Box',price:2,stock:10},operator,0,'product-request-0001');
    assert.equal(created.status,200);const id=created.body.data.id; imageProductId = id;
    const receipt = await call('/sync/receipt/product-request-0001', 'GET', undefined, operator);
    assert.equal(receipt.status, 200);
    assert.equal(receipt.body.data.replayed, true);
    assert.equal(receipt.body.data.data.id, id);
    assert.equal((await call('/sync/receipt/unknown-receipt-0001', 'GET', undefined, operator)).status, 404);
    const png = 'iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAQAAAC1HAwCAAAAC0lEQVR42mNk+A8AAQUBAScY42YAAAAASUVORK5CYII=';
    const imageBody = { data: `data:image/png;base64,${png}` };
    const image = await call(`/products/${id}/image`, 'POST', imageBody, admin, 1, 'image-request-0001');
    assert.equal(image.status, 200, JSON.stringify(image.body));
    const imageRetry = await call(`/products/${id}/image`, 'POST', imageBody, admin, 1, 'image-request-0001');
    assert.equal(imageRetry.status, 200);
    const oldImageUrl = image.body.data.image_url;
    assert.match(oldImageUrl, /^\/uploads\/products\/[A-Za-z0-9._-]+$/);
    assert.equal(oldImageUrl.startsWith('http://'), false);
    assert.equal(oldImageUrl.startsWith('https://'), false);
    assert.equal(db.backupData().products.find(product => product.id === id).image_url, oldImageUrl);
    const image2 = await call(`/products/${id}/image`, 'POST', { data: 'data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAYAAAAfFcSJAAAADUlEQVR4nGP4z8DwHwAFAAH/iZk9HQAAAABJRU5ErkJggg==' }, admin, 2, 'image-request-0002');
    assert.equal(image2.status, 200, JSON.stringify(image2.body));
    assert.notEqual(image2.body.data.image_url, oldImageUrl);
    assert.equal(fs.existsSync(path.join(__dirname, 'public', oldImageUrl.replace(/^\/uploads\//, 'uploads/'))), false);
    assert.equal(db.revision(), 3);
    assert.equal((await call(`/products/${id}/image`, 'POST', { data: 'data:image/png;base64,aGVsbG8=' }, admin, 3, 'image-request-0003')).status, 400);
    assert.equal((await call('/products','GET',undefined,viewer)).body.data.length,1);
    assert.equal((await call('/products','POST',{name:'Box',price:2,stock:10},operator,0,'product-request-0001')).body.data.id,id);
    assert.equal(db.revision(),3);
    const conflict = await call('/products','POST',{name:'Different'},operator,1,'product-request-0001');
    assert.equal(conflict.status,409);
    assert.equal(conflict.body.data.revision, db.revision());
    const both=await Promise.all([call('/stock/out','POST',{product_id:id,quantity:7},operator,3,'stock-request-one1'),call('/stock/out','POST',{product_id:id,quantity:7},admin,3,'stock-request-two2')]);
    assert.deepEqual(both.map(x=>x.status).sort(),[200,409]);
    assert.equal(db.getProduct(id).stock,3);
    assert.equal((await call('/stock/out','POST',{product_id:id,quantity:7},admin,4,'stock-request-new3')).status,400);
    assert.equal(db.getProduct(id).stock,3);
    assert.equal((await call('/suppliers','POST',{name:'Supplier',payable:10},operator,4,'supplier-request1')).status,403);
    const supplier=await call('/suppliers','POST',{name:'Supplier',payable:10},admin,4,'supplier-request1');
    assert.equal(supplier.status,200);
    assert.equal((await call(`/suppliers/${supplier.body.data.id}`,'PUT',{payable:0},operator,5,'settlement-req01')).status,403);
    assert.equal((await call(`/suppliers/${supplier.body.data.id}`,'PUT',{payable:0},admin,5,'settlement-req02')).status,200);
    const disk=fs.readFileSync(process.env.WAREHOUSE_DATA_FILE,'utf8');
    assert.throws(()=>db.transact({id:'test',username:'test'},'failure-request1','fp','6','test',()=>{db.updateProduct(id,{name:'Corrupted',price:-1});}),/无效/);
    assert.equal(db.getProduct(id).name,'Box');assert.equal(fs.readFileSync(process.env.WAREHOUSE_DATA_FILE,'utf8'),disk);
    const originalRename=fs.renameSync;
    fs.renameSync=()=>{throw new Error('Disk error');};
    assert.throws(()=>db.transact({id:'test',username:'test'},'failure-request2','fp','6','test',()=>db.updateProduct(id,{name:'Corrupted'})),/Disk error/);
    fs.renameSync=originalRename;
    assert.equal(db.getProduct(id).name,'Box');assert.equal(fs.readFileSync(process.env.WAREHOUSE_DATA_FILE,'utf8'),disk);
    const audit=await call('/audit','GET',undefined,admin);assert.equal(audit.status,200);assert(audit.body.data.items.some(e=>e.actor_name===(both[0].status===200?'operator':'admin')&&e.operation==='POST /stock/out'));
    const members=(await call('/team','GET',undefined,admin)).body.data;
    assert.equal((await call(`/team/${members.find(u=>u.username==='admin').id}`,'PUT',{disabled:true},admin)).status,400);
    assert.equal((await call(`/team/${members.find(u=>u.username==='operator').id}`,'PUT',{disabled:true},admin)).status,200);
    assert.equal((await call('/products','GET',undefined,operator)).status,401);
    assert.equal((await call('/auth/password','POST',{currentPassword:'Example-test-password!',password:'New-test-password!'},viewer)).status,200);
    assert.equal((await call('/products','GET',undefined,viewer)).status,401);
    let limitedResponse = null;
    for (let index = 0; index < 340 && !limitedResponse; index++) {
      const response = await fetch(origin + '/ledger', { method: 'POST', headers: { 'Content-Type': 'application/json', Authorization: `Bearer ${admin}`, 'X-Warehouse-Device': 'rate-test-device', 'Idempotency-Key': `rate-limit-${String(index).padStart(4, '0')}`, 'If-Match': String(db.revision()) }, body: JSON.stringify({ type: 'expense', amount: -1 }) });
      if (response.status === 429) limitedResponse = response;
      else await response.text();
    }
    assert.ok(limitedResponse, 'write rate limit should reject a burst');
    assert.equal(limitedResponse.headers.get('retry-after'), '60');
    delete require.cache[require.resolve('./db')]; const reopened=require('./db');assert.equal(reopened.getProduct(id).stock,3);assert.equal(reopened.revision(),6);
  } finally {
    const imageDir = path.join(__dirname, 'public', 'uploads', 'products');
    if (imageProductId !== null && fs.existsSync(imageDir)) for (const name of fs.readdirSync(imageDir)) if (name.startsWith(`${imageProductId}-`)) { try { fs.unlinkSync(path.join(imageDir, name)); } catch {} }
    await new Promise(r=>server.close(r)); server.closeAllConnections();
  }
});
